Прокидывание данных запроса в методы `get` / `post` хэндлеров
Hhhuuu/smart-proxy pull request #4
Opened 2020-10-13 09:04 UTC by svlitvinenko

Прокидываю `HttpServletRequest` и прочие данные запроса в методы, возвращающие ответы хэндлеров.

Resolves #2

2020-10-13 09:04 UTC, svlitvinenko commented
Зависит от #3

2020-10-13 10:39 UTC, Hhhuuu requested changes

2020-10-13 10:39 UTC, Hhhuuu commented on pom.xml
> +        </dependency>
Лучше оставить в PR только то, что касается задачи. Изменение связанные с kotlin не нужно

2020-10-13 10:39 UTC, Hhhuuu commented on src/main/java/com/simple/proxy/ProxyConfiguration.java
>  import com.simple.proxy.handlers.GetResponseHandler;
Можно этот файл удалить.

2020-10-13 10:39 UTC, Hhhuuu commented on src/main/java/com/simple/proxy/handlers/GetResponseHandler.java
> +import org.jetbrains.annotations.NotNull;
Если честно не очень нравится аннотация от jetbrains

2020-10-13 10:39 UTC, Hhhuuu commented on src/main/java/com/simple/proxy/handlers/PostResponseHandler.java
> +                    @NotNull String body,
Body и headers могут быть null

2020-10-13 10:39 UTC, Hhhuuu commented on src/main/java/com/simple/proxy/handlers/PostResponseHandler.java
> +     * Выполняет POST-запрос. Методы вызывается толкьо в случае,
Метод, только

2020-10-13 10:39 UTC, Hhhuuu commented on src/main/java/com/simple/proxy/handlers/PostResponseHandler.java
> +     * если {@link PostResponseHandler#matches(HttpServletRequest, String, Map)} вернул {@code true}.
Считаю лишним комментарий

2020-10-13 11:14 UTC, svlitvinenko commented on pom.xml
> +        </dependency>
Убрал

2020-10-13 11:14 UTC, svlitvinenko commented on src/main/java/com/simple/proxy/ProxyConfiguration.java
>  import com.simple.proxy.handlers.GetResponseHandler;
Оу, тут не додумался. Потом может? :D

2020-10-13 11:15 UTC, svlitvinenko commented on src/main/java/com/simple/proxy/handlers/GetResponseHandler.java
> +import org.jetbrains.annotations.NotNull;
Остановились на спринговых

2020-10-13 11:16 UTC, svlitvinenko commented on src/main/java/com/simple/proxy/handlers/PostResponseHandler.java
> +     * Выполняет POST-запрос. Методы вызывается толкьо в случае,
Спасибо. Убрал пояснение, т.к. оно уже есть в описании интерфейса.

2020-10-13 11:16 UTC, svlitvinenko commented on src/main/java/com/simple/proxy/handlers/PostResponseHandler.java
> +     * если {@link PostResponseHandler#matches(HttpServletRequest, String, Map)} вернул {@code true}.
Укоротил его.

2020-10-14 07:58 UTC, Hhhuuu requested changes

2020-10-14 07:58 UTC, Hhhuuu commented on src/main/java/com/simple/proxy/ProxyConfiguration.java
> +import org.springframework.lang.Nullable;
Предлагаю удалить этот файл вообще

2020-10-14 07:58 UTC, Hhhuuu commented on src/main/java/com/simple/proxy/handlers/PostResponseHandler.java
> +                    @NonNull Map<String, String> headers);
Могут быть null

2020-10-15 08:29 UTC, svlitvinenko commented on src/main/java/com/simple/proxy/handlers/PostResponseHandler.java
> +                    @NonNull Map<String, String> headers);
Спасибо. Невнимательность...

2020-10-15 08:29 UTC, svlitvinenko commented on src/main/java/com/simple/proxy/ProxyConfiguration.java
> +import org.springframework.lang.Nullable;
Удалил

2020-10-15 08:35 UTC, Hhhuuu approved these changes

2020-10-15 08:35 UTC, merged